---
- name: This play is using Molecule
  hosts: redhat_servers
  tasks:
    - name: Copy Hello package
      copy:
        src: "{{ playbook_dir }}/files/rpms/hello-2.6-3.fc17.x86_64.rpm"
        dest: /tmp/hello.rpm
        mode: 0777

    - name: Install Hello rpm
      yum:
        name: /tmp/hello.rpm
        state: present
        disable_gpg_check : true
