- name: Playbook with Docker tests
  hosts: localhost
#  vars:
#    platforms:
#      - name: molecule-ubuntu
#        image: ubuntu:latest

  tasks:
    - name: Get info on docker host
      community.docker.docker_host_info:
        docker_host: "tcp://host.docker.internal:2375"
        images: true
        verbose_output: false
      register: info

    - name: Docker info
      debug:
        var: info