- name: Playbook with Docker tests
  hosts: localhost
  environment:
    DOCKER_HOST: tcp://host.docker.internal:2375
  vars:
    platform:
      name: molecule-ubuntu
      image: ubuntu:18.04

  tasks:
    - name: Get info on docker host
      community.docker.docker_host_info:
        docker_host: "tcp://host.docker.internal:2375"
        images: true
        verbose_output: false
      register: docker_host_info

    - name: Debug Docker host info
      debug:
        var: docker_host_info
