usa:
  children:
    southeast:
      children:
        atlanta:
          hosts:
            host1:
              var_1: hello
            host2:
        raleigh:
          hosts:
            host2:
            host3:
      vars:
        some_server: foo.southeast.example.com
        halon_system_timeout: 30
        self_destruct_countdown: 60
        escape_pods: 2
    northeast:
    northwest:
    southwest: