---
platforms:
  - name: molecule-redhat
    image: miel1980/redhat-ssh-enabled:latest

provisioner:
  name: ansible
  inventory:
    links:
      hosts: inventory.ini

scenario:
  name: test-hello-is-present-docker
  test_sequence:
    - create
    - converge
    - verify
    - destroy