---
- name: Verify
  hosts: target4
#  connection: local
#  gather_facts: false
  vars:
    molecule_scenario: "{{ lookup('env', 'MOLECULE_SCENARIO_NAME') }}"
    molecule_test_directory: "{{ lookup('env', 'MOLECULE_VERIFIER_TEST_DIRECTORY') }}"
  tasks:
    - name: Debug
      debug:
        msg:
          - "molecule_scenario: {{ molecule_scenario }}"
          - "molecule_test_directory: {{ molecule_test_directory }}"


# TODO: DON'T FORGET TO INSTALL GOSS ON THE TARGET MACHINE. Goss is now part of the RedHat image, no need to install anymore...
# https://github.com/goss-org/goss > Installation > Manual installation



# TODO: First we need to install python3 on the target node, this is required by Ansible

    - name: Copy Goss test to guest
      copy:
        src: tests/test.yml
        dest: /tmp
        mode: 0777

    - name: Test with tests file
      goss:
        path: /tmp/test.yml
        format: junit
        output_file: /tmp/goss-junit.xml

    - name: Debug
      debug:
