---

 - include: repositories.yml

 - name: Install MySQL 5.7 DB Server
   #yum: name=mysql-community-server-5.6.35-2.el7 state=present
   yum: name=mysql-community-server state=present
   when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

 - name: Install MySQL Python Package
   yum: name=MySQL-python
