---
- name: My playbook
  hosts: alpine_servers_1
#  hosts: alpine_servers_1:!alpine_servers_2
#  hosts: alpine_servers_1[0]
  tasks:
    - name: Debug
      debug:
        msg:
          - "inventory_hostname: {{ inventory_hostname }}"
          - "group_names: {{ group_names }}"
          - "name: {{ name }}"
